In [1]:
#importing libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.17.1'

In [5]:
dataset=pd.read_csv('American_Express_User_Exit.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [7]:
#encoding gender using label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
print(X)


[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [8]:
#encoding geography by using one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [9]:
#splitting data into training set and test set(20%)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
#implementing ann
ann=tf.keras.models.Sequential()

In [12]:
#adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

In [13]:
#adding another hidden layer
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

In [14]:
#adding output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [15]:
#compiling ann
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [16]:
#training on training dataset
ann.fit(X_train,y_train,batch_size=32,epochs=120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.4022 - loss: 0.8395
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7919 - loss: 0.5204
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7971 - loss: 0.4738
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7996 - loss: 0.4553
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7962 - loss: 0.4511
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8051 - loss: 0.4270
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8017 - loss: 0.4315
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8097 - loss: 0.4225
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8088 - loss: 0.4226
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8142 - loss: 0.4096
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8163 - loss: 0.4140
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

In [17]:
print(ann.predict(sc.transform([[0.0,1.0,0.0,501,0,32,2,0.0,4,1,54550]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
[[False]]


In [19]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


In [20]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1507   66]
 [ 229  184]]


0.851460221550856